version: "3.7"

services:
  postgres:
    image: postgres:13.0
    ports:
      - "5432:5432"
    expose:
      - 5432
    env_file:
      - config.env
    volumes:
      - docker-example-data:/var/lib/postgresql/data
  app:
    image: docker-example
    ports:
      - 3000:3000
    environment:
      WAIT_HOSTS: postgres:5432
    env_file:
      - config.env
    depends_on:
      - postgres

volumes:
  docker-example-data:

