version: "3.7"

services:
  postgres:
    image: postgres:13.0
    expose:
      - 5432
    environment:
      POSTGRES_DB: go_in_docker_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    volumes:
      - godo-data:/var/lib/postgresql/data
  app:
    image: godo
    ports:
      - 3000:3000
    depends_on:
      - postgres

volumes:
  godo-data:

